[#-- Get current, parent, and grandparent page names for category lookup --]
[#assign currentPageName = content['@name']!]
[#assign parentPage = cmsfn.parent(content, "mgnl:page")!]
[#assign parentPageName = parentPage['@name']!]
[#assign grandparentPage = cmsfn.parent(parentPage, "mgnl:page")!]
[#assign grandparentPageName = grandparentPage['@name']!]

[#assign subcategories = []]
[#assign categoryPath = ""]

[#if currentPageName?has_content || parentPageName?has_content]
    [#assign jcrSession = ctx.getJCRSession("category")!]
    [#assign pathCandidates = []]
    [#if parentPageName?has_content]
        [#assign pathCandidates = pathCandidates + ["/" + parentPageName]]
        [#if grandparentPageName?has_content]
            [#assign pathCandidates = pathCandidates + ["/" + grandparentPageName + "/" + parentPageName]]
        [/#if]
    [/#if]
    [#if currentPageName?has_content]
        [#assign pathCandidates = pathCandidates + ["/" + currentPageName]]
    [/#if]
    [#list pathCandidates as path]
        [#if jcrSession?has_content && jcrSession.nodeExists(path)]
            [#assign categoryPath = path]
            [#break]
        [/#if]
    [/#list]
    [#if categoryPath?has_content && jcrSession?has_content]
        [#assign currentCategory = jcrSession.getNode(categoryPath)]
        [#assign subcategories = cmsfn.children(currentCategory, "mgnl:category")!]
    [/#if]
[/#if]

[#-- Display components first (includes auto-generated welcome text) --]
[#if components?has_content]
    [#list components as component]
        [@cms.component content=component /]
    [/#list]
[/#if]

[#-- Display subcategories --]
[#if subcategories?has_content]
    <div class="mb-8 space-y-4">
        [#list subcategories as subcategory]
            [#assign subcatName = subcategory.name!]
            [#assign subcatTitle = subcategory.title!subcatName]
            [#assign pageNode = ""]
            [#list [currentPageName!, parentPageName!] as baseName]
                [#if baseName?has_content]
                    [#assign pageNode = cmsfn.nodeByPath("/home/" + baseName + "/" + subcatName)!]
                    [#if pageNode?has_content][#break][/#if]
                [/#if]
            [/#list]
            [#assign categoryLink = (pageNode?has_content)?then(cmsfn.link(pageNode)!, "")]
            
            <div class="border border-gray-200 rounded-lg p-4 hover:shadow-lg transition-shadow">
                [#if categoryLink?has_content]<a href="${categoryLink}" class="block">[/#if]
                    <h3 class="text-xl font-semibold text-dark-teal mb-2">${subcatTitle}</h3>
                    [#if subcategory.description?has_content]
                        <p class="text-gray-600">${subcategory.description}</p>
                    [/#if]
                [#if categoryLink?has_content]</a>[/#if]
            </div>
        [/#list]
    </div>
[/#if]